### ISSUE TITLE
무엇을 만드는 것인가?

### ISSUE THREAD

**Issue by simongs** [nerdhorizon/TimeScheduler#1]
궁금

**Comment by nerdhorizon** [comment]
뽀모도로 비슷한 스케쥴 관리 프로그램 만들어 볼까 하고 있어요

**Comment by nerdhorizon** [comment]
ㅋㅋ 이거 신기하네요 이슈 생성기인듯요

**Comment by simongs** [comment]
ㅇㅇ github 강력하다 ㅋ 근데 gmail을 잘 안읽어서 알림을 더 확실하게 받는 방법을 모르겠네
